In [1]:
import torch

In [13]:
def heat_equation(T, dx, alpha):
    nx = T.shape[0]
    f = torch.zeros(nx)

    f[1:-1] = alpha/dx ** 2 * (T[:-2] - 2 *T[1:-1] + T[2:])
    f[0] = 0
    f[-1] = 0
    return f

def forward_solver(alpha, T0, dx, dt, nt):
    T = T0
    for _ in range(nt):
        print("inside loop")
        result = heat_equation(T, dx, alpha)
        print(result)
        T = T + dt * heat_equation(T, dx, alpha)
    return T

In [14]:


lx = 1.0
nx = 21
dx = lx / (nx - 1)
x = torch.linspace(0., lx, nx)

true_alpha = torch.tensor(0.4)
fourier = 0.49
dt = fourier * dx**2 / true_alpha
nt = 100

T0 = torch.sin(2 * torch.tensor(3.1459) * x)


In [16]:
print(T0)

tensor([ 0.0000,  0.3094,  0.5885,  0.8098,  0.9516,  1.0000,  0.9503,  0.8072,
         0.5850,  0.3053, -0.0043, -0.3135, -0.5920, -0.8123, -0.9529, -1.0000,
        -0.9489, -0.8047, -0.5815, -0.3012,  0.0086])


In [15]:
nt = 1
forward_solver(true_alpha, T0, dx, dt, nt)

inside loop
tensor([  0.0000,  -4.8594,  -9.2418, -12.7172, -14.9443, -15.7045, -14.9233,
        -12.6773,  -9.1871,  -4.7950,   0.0676,   4.9237,   9.2965,  12.7566,
         14.9649,  15.7042,  14.9021,  12.6373,   9.1321,   4.7306,   0.0000])


tensor([ 0.0000,  0.2945,  0.5602,  0.7708,  0.9058,  0.9519,  0.9046,  0.7684,
         0.5569,  0.2906, -0.0041, -0.2984, -0.5635, -0.7732, -0.9071, -0.9519,
        -0.9033, -0.7660, -0.5535, -0.2867,  0.0086])

In [5]:
u_true = forward_solver(true_alpha, T0, dx, dt, nt)


In [6]:
def loss(alpha):
    u_pred = forward_solver(alpha, T0, dx, dt, nt)
    return torch.sum((u_pred - u_true)**2) / nx


In [7]:
alpha = torch.tensor(0.1, requires_grad=True)
lr = 0.01
epochs = 1000

In [8]:
from tqdm import tqdm

for i in tqdm(range(epochs)):
    l = loss(alpha)
    l.backward()
    with torch.no_grad():
        alpha -= lr * alpha.grad
        alpha.grad.zero_()


100%|██████████| 1000/1000 [00:00<00:00, 4421.05it/s]


In [9]:
alpha

tensor(0.1385, requires_grad=True)